## Artix 7 100T constraints file, autogenerated for SADIE
## Device/Package xc7a100tftg256 6/6/2012 10:19:27

#Copied from the arty one lol
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
 set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets io_gpio3_OBUF]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports { reset }];
#Clock
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports { clock }];
create_clock -add -name sys_clk_pin -period 62.5 \
    -waveform {0 31.25} [get_ports { clock }];
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_IBUF];
# SPI
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports { io_spi_mosi }];      #IO_L11P_T1_SRCC_15 Sch=jb_p[1]
set_property -dict {PACKAGE_PIN N6 IOSTANDARD LVCMOS33} [get_ports { io_spi_clk  }];      #IO_L12P_T1_MRCC_15 Sch=jb_p[2]
set_property -dict {PACKAGE_PIN P8 IOSTANDARD LVCMOS33} [get_ports { io_spi_cs_n }];      #IO_L12N_T1_MRCC_15 Sch=jb_n[2]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports { io_spi_clock }];
set_property -dict {PACKAGE_PIN N9 IOSTANDARD LVCMOS33} [get_ports { io_spi_slave_select }];
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports { io_spi_data_bit }];
set_property -dict {PACKAGE_PIN P9 IOSTANDARD LVCMOS33} [get_ports { io_spi_debug }];
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets io_spi_clk_IBUF]

# GPIO
#set_property -dict { PACKAGE_PIN R10   IOSTANDARD LVCMOS33 } [get_ports { io_gpio0 }];
#set_property -dict { PACKAGE_PIN R11   IOSTANDARD LVCMOS33 } [get_ports { io_gpio1 }];
#set_property -dict { PACKAGE_PIN N9   IOSTANDARD LVCMOS33 } [get_ports { io_gpio2 }];
